// <auto-generated />
using System;
using System.Collections.Generic;
using EFR.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFR.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828140636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFR.Api.Models.Enitites.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AlunoId"));

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EscolinhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("AlunoId");

                    b.HasIndex("EscolinhaId");

                    b.HasIndex("PlanoId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Aula", b =>
                {
                    b.Property<int>("AulaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AulaId"));

                    b.Property<DateTime>("HoraFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer");

                    b.HasKey("AulaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Configuracao", b =>
                {
                    b.Property<int>("ConfiguracaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracaoId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscolinhaId")
                        .HasColumnType("integer");

                    b.Property<bool>("LembreteChamadas")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarCobrancas")
                        .HasColumnType("boolean");

                    b.Property<int>("TempoChuvaHoras")
                        .HasColumnType("integer");

                    b.HasKey("ConfiguracaoId");

                    b.HasIndex("EscolinhaId")
                        .IsUnique();

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Escolinha", b =>
                {
                    b.Property<int>("EscolinhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EscolinhaId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(77)
                        .HasColumnType("character varying(77)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoChavePix")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("EscolinhaId");

                    b.ToTable("Escolinhas");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Plano", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Duracao")
                        .HasColumnType("integer");

                    b.Property<int>("EscolinhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("PlanoId");

                    b.HasIndex("EscolinhaId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Turma", b =>
                {
                    b.Property<int>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TurmaId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("EscolinhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TurmaId");

                    b.HasIndex("EscolinhaId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilizadorId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("BiometriaAtivada")
                        .HasColumnType("boolean");

                    b.Property<string>("Cref")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("EscolinhaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("UtilizadorId");

                    b.HasIndex("EscolinhaId");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("TurmaUtilizador", b =>
                {
                    b.Property<int>("ProfessoresUtilizadorId")
                        .HasColumnType("integer");

                    b.Property<int>("TurmasTurmaId")
                        .HasColumnType("integer");

                    b.HasKey("ProfessoresUtilizadorId", "TurmasTurmaId");

                    b.HasIndex("TurmasTurmaId");

                    b.ToTable("TurmaUtilizador");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Aluno", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Escolinha", "Escolinha")
                        .WithMany("Alunos")
                        .HasForeignKey("EscolinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFR.Api.Models.Enitites.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFR.Api.Models.Enitites.Turma", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId");

                    b.Navigation("Escolinha");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Aula", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Utilizador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFR.Api.Models.Enitites.Turma", "Turma")
                        .WithMany("Aulas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Configuracao", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Escolinha", "Escolinha")
                        .WithOne("Configuracao")
                        .HasForeignKey("EFR.Api.Models.Enitites.Configuracao", "EscolinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escolinha");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Plano", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Escolinha", "Escolinha")
                        .WithMany()
                        .HasForeignKey("EscolinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escolinha");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Turma", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Escolinha", "Escolinha")
                        .WithMany("Turmas")
                        .HasForeignKey("EscolinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escolinha");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Utilizador", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Escolinha", "Escolinha")
                        .WithMany("Professores")
                        .HasForeignKey("EscolinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escolinha");
                });

            modelBuilder.Entity("TurmaUtilizador", b =>
                {
                    b.HasOne("EFR.Api.Models.Enitites.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("ProfessoresUtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFR.Api.Models.Enitites.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasTurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Escolinha", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Configuracao");

                    b.Navigation("Professores");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EFR.Api.Models.Enitites.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Aulas");
                });
#pragma warning restore 612, 618
        }
    }
}
